name: plexmediaserver
version: 1.2.2.2857-d34b464-1
summary: Unofficial snap for the Plex media server
architectures: [amd64]
description: |
  Plex organizes all of your personal media so you can easily
  access and enjoy it. See https://www.plex.tv/
confinement: devmode
grade: devel

apps:
  server:
    command: bin/server.sh
    daemon: simple
    plugs:
      - home
      - network-bind

parts:
  common:
    plugin: dump
    source: .
    snap:
      - bin/server.sh
  plexmediaserver:
    plugin: make
    source: .
